### ISSUE TITLE
API: Update A1 Entities

### ISSUE THREAD

**Issue by smiththay** [UK-SBCoA/uniform-data-set-dotnet-api#26]
Update A1 entity class with all the properties. Ensure correct data types and validation annotations.
[https://github.com/naccdata/uniform-data-set/blob/main/forms/uds/a1/form_a1_ivp_questions_and%20vars.csv](https://github.com/naccdata/uniform-data-set/blob/main/forms/uds/a1/form_a1_ivp_questions_and%20vars.csv)

Variables Added in UDS4:

CHLDHDCTRY
RACEWHITE
ETHGERMAN
ETHIRISH
ETHENGLISH
ETHITALIAN
ETHPOLISH
ETHFRENCH
ETHWHIOTH
ETHWHIOTHX
ETHISPANIC
ETHMEXICAN
ETHPUERTO
ETHCUBAN
ETHSALVA
ETHDOMIN
ETHCOLOM
ETHHISOTH
ETHHISOTHX
RACEBLACK
ETHAFAMER
ETHJAMAICA
ETHHAITIAN
ETHNIGERIA
ETHETHIOP
ETHSOMALI
ETHBLKOTH
ETHBLKOTHX
RACEASIAN
ETHCHINESE
ETHFILIP
ETHINDIA
ETHVIETNAM
ETHKOREAN
ETHJAPAN
ETHASNOTH
ETHASNOTHX
RACEAIAN
RACEAIANX
RACEMENA
ETHLEBANON
ETHIRAN
ETHEGYPT
ETHSYRIA
ETHMOROCCO
ETHISRAEL
ETHMENAOTH
ETHMENAOTX
RACENHPI
ETHHAWAII
ETHSAMOAN
ETHCHAMOR
ETHTONGAN
ETHFIJIAN
ETHMARSHAL
ETHNHPIOTH
ETHNHPIOTX
RACEUNKN
GENMAN
GENWOMAN
GENTRMAN
GENTRWOMAN
GENNONBI
GENTWOSPIR
GENOTH
GENOTHX
GENDKN
GENNOANS
BIRTHSEX
INTERSEX
SEXORNGAY
SEXORNHET
SEXORNBI
SEXORNTWOS
SEXORNOTH
SEXORNOTHX
SEXORNDNK
SEXORNNOAN
PREDOMLAN
PREDOMLANX
LVLEDUC
SERVED
MEDVA
EXRTIME
MEMWORS
MEMTROUB
MEMTEN
ADISTATE
ADINAT
PRIOCC
REFERSCX
REFLEARNED
REFCTRSOCX
REFCTRREGX
REFOTHWEBX
REFOTHMEDX
REFOTHREGX
REFOTHX

Variables Deleted from UDS#:

REASON
LEARNED
PRESTAT
PRESPART
HISPOR
HISPORX
RACEX
RACESEC
RACESECX
RACETER
RACETERX
PRIMLANX

**Comment by mlan225** [comment]
@smiththay talked with @ashleybot and it seems like whenever this branch gets reviewed and ready to merge in you will want to pull in main to get the new version (1.5.5), and then update the version in this PR (to 1.5.6) before merging into main 👍
